### PR TITLE
Some littles improvments

### PR DESCRIPTION
**Pull request by olivierperez**
I do some changes I needed on my own instance:
- Implement a new system to configure what are the times allowed when creating a new room.
- Some rework of the seed generation
- Split conf.php into 2 files conf.php and constants.php

### CODE REVIEW

**Comment by olivierperez** [comment]
Hi @HowTommy did you see my merge request please?

**Comment by HowTommy** [comment]
Hello,
I'll check this out today.
Regards

**Comment by olivierperez** [comment]
Ping :smile:

**Comment by kadogo** [comment]
It is possible that this part.
Copy <strong>inc/config.template.php</strong> into <strong>inc/config.php</strong>, and don't forget to <strong>customize it</strong>.

Must change in:
Copy <strong>inc/config.template.php</strong> into <strong>inc/conf.php</strong>, and don't forget to <strong>customize it</strong>.

**Comment by HowTommy** [comment]
One year later: merged done, thanks!

I am also currently adding a "Report" button :)

**Pull request merged**
